\input texinfo
@settitle Sample Manual 1.0

@copying
This is the description of the application 3DViewer v2.0

Copyright @copyright{} 2023 Egor&Ruslan&Sergey (school 21, Novosibirsk).
@end copying

@titlepage
@title Description 3DViewer v1.0
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage



@node Top
@top GNU Sample

This manual is for GNU Sample
(version @value{VERSION}, @value{UPDATED}).



@node Description 3DViewer v1.0
@section Description 3DViewer v2.0

The application provides a graphical 3DViewer with support for the following features:

1. Load a wireframe model from an obj format file (only vertexes and edges list support).

2. Move the model by a specified distance relative to the X, Y, Z axes.

3. Rotate the model by a specified angle relative to its X, Y, Z axes.

4. Scale the model by a specified value.

5. Choose the type of projection (parallel and central).

6. Choose the type (solid, dotted), color and thickness of the edges.

7. Choose the display method (absent, circle, square), color, and size of vertices.

8. Choose the background color.

9. Save the obtained ("rendered") images to a file in bmp and jpeg formats.

10. Record small "screencasts" as gif-animation.


@bye